//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mid_Project.Models.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class HotelReg
    {
        [Required(ErrorMessage = "Please provide ID")]
        public int Id { get; set; }
        [Required(ErrorMessage = "Please provide Name")]
        public string Name { get; set; }
        public string Password { get; set; }
        [Required(ErrorMessage = "Please provide Type")]
        public string Type { get; set; }
        [Required(ErrorMessage = "Please provide Place")]
        public string Place { get; set; }
        [Required(ErrorMessage = "Please enter Student Address")]
        [StringLength(50, ErrorMessage = "Only 50 character are allowed")]
        public string Address { get; set; }
  
        public string Phone { get; set; }
       
        public string Email { get; set; }
    }
}
