//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mid_Task.Models.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AccountantList
    {
        
        public int Id { get; set; }

        [Required(ErrorMessage = "Please provide Name")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Please provide Password")]
        public string Password { get; set; }
        [Required(ErrorMessage = "Please provide Phone")] 
        public string Phone { get; set; }

        [Required(ErrorMessage = "Please provide Email")]
        public string Email { get; set; }
        public string Gender { get; set; }
        public string OtherInfo { get; set; }
        public string DoB { get; set; }
    }
}
